on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: fail
        run: |
            false
