on:
    merge_group:
        types: [checks_requested]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Say hello word
        run: |
            echo "Hello word"
