on:
    pull_request:
    merge_group:
        types: [checks_requested]

jobs:
  daily-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: fail
        run: |
            false
